In [1]:
import pandas as pd
import numpy as np
import difflib

In [2]:
amenities = pd.read_json("food-amenities-vancouver.json", lines=True)
amenities

,lat,lon,amenity,name,tags
0,49.185144,-123.130217,restaurant,0755 Restaurant & Lounge,"{'addr:housenumber': '3779', 'addr:street': 'S..."
1,49.193752,-123.121261,cafe,1029 Cafe,{}
2,49.281603,-123.132898,bar,1181,"{'addr:housenumber': '1181', 'website': 'http:..."
3,49.260301,-123.096684,pub,12 Kings Pub,{'opening_hours': 'Su-Th 12:00-01:00; Fr-Sa 12...
4,49.284169,-123.107343,bar,131 Water Kitchen & Bar,"{'addr:housenumber': '131', 'addr:street': 'Wa..."
...,...,...,...,...,...
5080,49.059230,-122.492277,fast_food,strEATS Aldergrove,"{'addr:housenumber': '26426', 'website': 'http..."
5081,49.230169,-123.004036,restaurant,trattoria Burnaby,"{'cuisine': 'italian', 'name:en': 'trattoria B..."
5082,49.249358,-122.867573,restaurant,yoko sushi,"{'addr:province': 'B.C.', 'addr:housenumber': ..."
5083,49.272419,-123.134633,cafe,à la mode,{'indoor': 'yes'}
5084,49.180830,-123.134178,fast_food,敘香園,{'name:en': '敘香園'}

In [3]:
canadian_chains = pd.read_csv("CanadaFoodChains.csv")
canadian_chains

                 foodChains
0                 241 Pizza
1                       A&W
2               Baton Rouge
3               BeaverTails
4          Queues de Castor
..                      ...
78  Urban Sparq Hospitality
79     Wild Wing Resturants
80            Wimpy's Diner
81               White Spot
82                The Works

[83 rows x 1 columns]

In [4]:
#filter canadian food chains
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, canadian_chains['foodChains'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
canadian_chains = amenities[amenities['closest_name'] != '']
canadian_chains.to_json('chain-resturants-vancouver.json', orient='records', lines=True)
canadian_chains

,lat,lon,amenity,name,tags,closest_name
4926,49.213000,-122.921101,restaurant,White Spot,"{'brand:wikidata': 'Q7995414', 'internet_acces...",White Spot
4932,49.276156,-123.128164,restaurant,White Spot,"{'brand:wikidata': 'Q7995414', 'addr:housenumb...",White Spot
4911,49.280070,-122.969769,restaurant,White Spot,"{'brand:wikidata': 'Q7995414', 'addr:housenumb...",White Spot
4912,49.045922,-122.782154,restaurant,White Spot,"{'brand:wikidata': 'Q7995414', 'addr:housenumb...",White Spot
4913,49.129415,-122.318647,restaurant,White Spot,"{'brand:wikidata': 'Q7995414', 'website': 'htt...",White Spot
...,...,...,...,...,...,...
70,49.279619,-123.117481,fast_food,A&W,"{'brand:wikidata': 'Q2818848', 'addr:housenumb...",A&W
72,49.191719,-123.111856,fast_food,A&W,"{'delivery': 'no', 'addr:housenumber': '100-30...",A&W
73,49.154043,-123.124961,fast_food,A&W,{},A&W
74,49.219267,-123.040835,fast_food,A&W,"{'brand:wikidata': 'Q2818848', 'internet_acces...",A&W
71,49.276982,-122.855011,fast_food,A&W,{},A&W

In [5]:
# filter different kinds of food chains in North America (american, arcade, asian, etc.)
# don't output json if comparison is empty

In [6]:
american = pd.read_csv("american.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, american['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
american = amenities[amenities['closest_name'] != '']
american.to_json('american.json', orient='records', lines=True)
american

,lat,lon,amenity,name,tags,closest_name
1918,49.263082,-123.126417,restaurant,Johnny Rockets,"{'brand:wikidata': 'Q1051593', 'addr:housenumb...",Johnny Rockets
1917,49.279751,-123.123526,restaurant,Johnny Rockets,"{'brand:wikidata': 'Q1051593', 'addr:housenumb...",Johnny Rockets

In [7]:
arcade = pd.read_csv("arcade-game-centers.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, arcade['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
arcade = amenities[amenities['closest_name'] != '']
arcade.to_json('arcade.json', orient='records', lines=True)
arcade

,lat,lon,amenity,name,tags,closest_name
846,49.11765,-122.668977,restaurant,Chuck E. Cheese's,"{'brand:wikidata': 'Q2438391', 'addr:housenumb...",Chuck E. Cheese's

In [8]:
asian_ff = pd.read_csv("asian-fast-food.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, asian_ff['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
asian_ff = amenities[amenities['closest_name'] != '']
asian_ff.to_json('asian_fast_food.json', orient='records', lines=True)
asian_ff

,lat,lon,amenity,name,tags,closest_name
3000,49.226971,-123.128746,restaurant,Phở Hòa,"{'brand:wikidata': 'Q55629932', 'name:vi': 'Ph...",Phở Hòa
3002,49.191681,-122.823399,restaurant,Phở Hòa,"{'brand:wikidata': 'Q55629932', 'name:vi': 'Ph...",Phở Hòa
3001,49.177490,-123.129286,restaurant,Phở Hòa,"{'brand:wikidata': 'Q55629932', 'name:vi': 'Ph...",Phở Hòa
3003,49.189941,-122.847175,restaurant,Phở Hòa,"{'brand:wikidata': 'Q55629932', 'name:vi': 'Ph...",Phở Hòa
2297,49.049839,-122.311703,fast_food,Manchu Wok,"{'brand:wikidata': 'Q6747622', 'website': 'htt...",Manchu Wok
2296,49.225828,-122.996940,fast_food,Manchu Wok,"{'brand:wikidata': 'Q6747622', 'level': '1', '...",Manchu Wok
2298,49.187115,-122.849357,fast_food,Manchu Wok,"{'brand:wikidata': 'Q6747622', 'brand:wikipedi...",Manchu Wok
2299,49.114373,-122.675294,fast_food,Manchu Wok,"{'brand:wikidata': 'Q6747622', 'addr:housenumb...",Manchu Wok

In [9]:
asian_fusion = pd.read_csv("asian-fusion.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, asian_fusion['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
asian_fusion = amenities[amenities['closest_name'] != '']
#asian_fusion.to_json('asian_fusion.json', orient='records', lines=True)
asian_fusion

Empty DataFrame
Columns: [lat, lon, amenity, name, tags, closest_name]
Index: []

In [10]:
baked_goods = pd.read_csv("baked-goods-fast-food.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, baked_goods['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
baked_goods = amenities[amenities['closest_name'] != '']
#baked_goods.to_json('baked_goods.json', orient='records', lines=True)
baked_goods

Empty DataFrame
Columns: [lat, lon, amenity, name, tags, closest_name]
Index: []

In [11]:
bar_brewpub = pd.read_csv("bar-brewpub.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, bar_brewpub['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
bar_brewpub = amenities[amenities['closest_name'] != '']
#bar_brewpub.to_json('bar_brewpub.json', orient='records', lines=True)
bar_brewpub

Empty DataFrame
Columns: [lat, lon, amenity, name, tags, closest_name]
Index: []

In [12]:
beef = pd.read_csv("beef-fast-food.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, beef['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
beef = amenities[amenities['closest_name'] != '']
#beef.to_json('beef.json', orient='records', lines=True)
beef

Empty DataFrame
Columns: [lat, lon, amenity, name, tags, closest_name]
Index: []

In [13]:
beverages = pd.read_csv("beverages-fast-food.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, beverages['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
beverages = amenities[amenities['closest_name'] != '']
beverages.to_json('beverages.json', orient='records', lines=True)
beverages

,lat,lon,amenity,name,tags,closest_name
4608,49.091952,-122.957650,cafe,Tim Hortons,"{'brand:wikidata': 'Q175106', 'cuisine': 'coff...",Tim Hortons
4562,49.249466,-123.115648,cafe,Tim Hortons,"{'brand:wikidata': 'Q175106', 'cuisine': 'coff...",Tim Hortons
4564,49.197184,-123.175483,cafe,Tim Hortons,"{'brand:wikidata': 'Q175106', 'addr:housenumbe...",Tim Hortons
4598,49.025132,-122.266143,fast_food,Tim Hortons,"{'website': 'https://www.timhortons.com/', 're...",Tim Hortons
4566,49.182145,-122.843993,cafe,Tim Hortons,"{'brand:wikidata': 'Q175106', 'addr:housenumbe...",Tim Hortons
...,...,...,...,...,...,...
2764,49.324905,-123.136894,juice_bar,Orange Julius,"{'wheelchair': 'yes', 'shop': 'beverages', 'le...",Orange Julius
995,49.274016,-123.122343,fast_food,DQ Orange Julius,"{'addr:housenumber': '1217', 'drive_through': ...",Orange Julius
996,49.049537,-122.311749,fast_food,DQ Orange Julius,{'official_name': 'Dairy Queen Orange Julius T...,Orange Julius
2757,49.227280,-123.000180,bar,Orange Julius,"{'level': '0', 'name:en': 'Orange Julius'}",Orange Julius
2758,49.225784,-122.997807,fast_food,Orange Julius,"{'brand:wikidata': 'Q3355059', 'level': '1', '...",Orange Julius

In [14]:
chicken = pd.read_csv("chicken.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, chicken['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
chicken = amenities[amenities['closest_name'] != '']
#chicken.to_json('chicken.json', orient='records', lines=True)
chicken

Empty DataFrame
Columns: [lat, lon, amenity, name, tags, closest_name]
Index: []

In [15]:
breakfast = pd.read_csv("breakfast.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, breakfast['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
breakfast = amenities[amenities['closest_name'] != '']
breakfast.to_json('breakfast.json', orient='records', lines=True)
breakfast

,lat,lon,amenity,name,tags,closest_name
1773,49.046370,-122.801681,restaurant,IHOP,"{'brand:wikidata': 'Q1185675', 'addr:housenumb...",IHOP
1774,49.164470,-123.136162,restaurant,IHOP,"{'brand:wikidata': 'Q1185675', 'addr:housenumb...",IHOP
1775,49.109716,-122.678902,restaurant,IHOP,"{'brand:wikidata': 'Q1185675', 'addr:housenumb...",IHOP
1092,49.223098,-122.982169,restaurant,Denny's,"{'brand:wikidata': 'Q1189695', 'cuisine': 'ame...",Denny's
1096,49.188181,-123.111680,restaurant,Denny's,"{'addr:housenumber': '10211', 'addr:street': '...",Denny's
1099,49.163706,-122.660481,restaurant,Denny's,"{'brand:wikidata': 'Q1189695', 'addr:housenumb...",Denny's
1095,49.263850,-123.144850,restaurant,Denny's,"{'brand:wikidata': 'Q1189695', 'addr:housenumb...",Denny's
1091,49.280210,-123.131197,restaurant,Denny's,"{'brand:wikidata': 'Q1189695', 'internet_acces...",Denny's
1093,49.157641,-122.890743,restaurant,Denny's,"{'brand:wikidata': 'Q1189695', 'cuisine': 'ame...",Denny's
1089,49.053033,-122.317056,restaurant,Denny's,"{'opening_hours': '24/7', 'cuisine': 'american...",Denny's
1090,49.127370,-122.845240,restaurant,Denny's,"{'name:en': 'Denny's', 'addr:street': 'King Ge...",Denny's
1098,49.117023,-122.675109,restaurant,Denny's,"{'brand:wikidata': 'Q1189695', 'addr:housenumb...",Denny's
1094,49.056215,-122.380711,restaurant,Denny's,"{'brand:wikidata': 'Q1189695', 'addr:housenumb...",Denny's
1097,49.263225,-123.133390,restaurant,Denny's,"{'brand:wikidata': 'Q1189695', 'addr:housenumb...",Denny's

In [16]:
caribbean = pd.read_csv("caribbean.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, caribbean['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
caribbean = amenities[amenities['closest_name'] != '']
#caribbean.to_json('caribbean.json', orient='records', lines=True)
caribbean

Empty DataFrame
Columns: [lat, lon, amenity, name, tags, closest_name]
Index: []

In [17]:
chicken_ff = pd.read_csv("chicken-fast-food.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, chicken_ff['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
chicken_ff = amenities[amenities['closest_name'] != '']
chicken_ff.to_json('chicken_fast_food.json', orient='records', lines=True)
chicken_ff

,lat,lon,amenity,name,tags,closest_name
3119,49.038444,-122.274552,fast_food,Popeyes,"{'official_name': 'Popeyes Louisiana Kitchen',...",Popeyes
3116,49.254660,-122.737900,fast_food,Popeyes,"{'brand:wikidata': 'Q1330910', 'official_name'...",Popeyes
3117,49.118801,-122.823760,fast_food,Popeyes,"{'brand:wikidata': 'Q1330910', 'official_name'...",Popeyes
3118,49.120990,-122.663999,fast_food,Popeyes,"{'brand:wikidata': 'Q1330910', 'addr:province'...",Popeyes
1950,49.167367,-122.800797,fast_food,KFC,"{'brand:wikidata': 'Q524757', 'addr:housenumbe...",KFC
1959,49.187192,-122.849834,fast_food,KFC,"{'brand:wikidata': 'Q524757', 'alt_name': 'Ken...",KFC
1962,49.161493,-122.890833,fast_food,KFC,"{'brand:wikidata': 'Q524757', 'alt_name': 'Ken...",KFC
1964,49.103946,-122.730542,fast_food,KFC,"{'brand:wikidata': 'Q524757', 'alt_name': 'Ken...",KFC
1952,49.243473,-123.062172,fast_food,KFC,"{'brand:wikidata': 'Q524757', 'alt_name': 'Ken...",KFC
1961,49.281233,-123.132309,fast_food,KFC,"{'brand:wikidata': 'Q524757', 'addr:housenumbe...",KFC
1966,49.163191,-122.661248,fast_food,KFC,"{'brand:wikidata': 'Q524757', 'addr:housenumbe...",KFC
1958,49.225612,-123.077724,fast_food,KFC,"{'brand:wikidata': 'Q524757', 'alt_name': 'Ken...",KFC
1947,49.194597,-122.845707,fast_food,KFC,"{'brand:wikidata': 'Q524757', 'website': 'http...",KFC
1955,49.277890,-122.795230,fast_food,KFC,"{'brand:wikidata': 'Q524757', 'alt_name': 'Ken...",KFC
1956,49.262628,-123.087466,fast_food,KFC,"{'brand:wikidata': 'Q524757', 'alt_name': 'Ken...",KFC
1951,49.139861,-123.137394,fast_food,KFC,"{'brand:wikidata': 'Q524757', 'cuisine': 'chic...",KFC
1963,49.189366,-122.802261,fast_food,KFC,"{'brand:wikidata': 'Q524757', 'alt_name': 'Ken...",KFC
1965,49.038536,-122.270425,fast_food,KFC,"{'brand:wikidata': 'Q524757', 'alt_name': 'Ken...",KFC
1957,49.217230,-122.606536,fast_food,KFC,"{'brand:wikidata': 'Q524757', 'addr:housenumbe...",KFC
1949,49.134323,-122.887236,fast_food,KFC,"{'brand:wikidata': 'Q524757', 'addr:housenumbe...",KFC
1948,49.135254,-122.846059,fast_food,KFC,"{'brand:wikidata': 'Q524757', 'brand:wikipedia...",KFC
1953,49.114245,-122.675488,fast_food,KFC,"{'brand:wikidata': 'Q524757', 'addr:housenumbe...",KFC
1954,49.263577,-122.887004,fast_food,KFC,"{'brand:wikidata': 'Q524757', 'alt_name': 'Ken...",KFC
1960,49.225420,-122.996970,fast_food,KFC,"{'brand:wikidata': 'Q524757', 'alt_name': 'Ken...",KFC
857,49.251204,-122.892545,fast_food,Church's Chicken,"{'brand:wikidata': 'Q1089932', 'addr:province'...",Church's Chicken
851,49.282430,-122.800392,fast_food,Church's Chicken,"{'brand:wikidata': 'Q1089932', 'addr:housenumb...",Church's Chicken
852,49.156266,-122.889970,fast_food,Church's Chicken,"{'brand:wikidata': 'Q1089932', 'addr:province'...",Church's Chicken
856,49.266855,-123.009284,fast_food,Church's Chicken,"{'brand:wikidata': 'Q1089932', 'addr:province'...",Church's Chicken
853,49.198933,-122.810257,fast_food,Church's Chicken,"{'brand:wikidata': 'Q1089932', 'wheelchair': '...",Church's Chicken
848,49.194262,-122.844800,fast_food,Church's Chicken,"{'addr:housenumber': '10542', 'website': 'http...",Church's Chicken
849,49.170957,-123.181557,fast_food,Church's Chicken,"{'wheelchair': 'yes', 'addr:housenumber': '367...",Church's Chicken
858,49.232523,-123.090106,fast_food,Church's Chicken,"{'addr:housenumber': '5704', 'website': 'http:...",Church's Chicken
847,49.219600,-122.968018,fast_food,Church's Chicken,"{'brand:wikidata': 'Q1089932', 'addr:housenumb...",Church's Chicken
850,49.254145,-123.101278,fast_food,Church's Chicken,"{'brand:wikidata': 'Q1089932', 'addr:housenumb...",Church's Chicken
855,49.280984,-123.057420,fast_food,Church's Chicken,"{'brand:wikidata': 'Q1089932', 'brand:wikipedi...",Church's Chicken
854,49.155299,-123.123732,fast_food,Church's Chicken,{'cuisine': 'chicken'},Church's Chicken

In [18]:
european = pd.read_csv("european.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, european['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
european = amenities[amenities['closest_name'] != '']
#european.to_json('european.json', orient='records', lines=True)
european

Empty DataFrame
Columns: [lat, lon, amenity, name, tags, closest_name]
Index: []

In [19]:
frozen_desserts = pd.read_csv("frozen-desserts-fast-food.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, frozen_desserts['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
frozen_desserts = amenities[amenities['closest_name'] != '']
frozen_desserts.to_json('frozen_desserts.json', orient='records', lines=True)
frozen_desserts

,lat,lon,amenity,name,tags,closest_name
5008,49.189652,-122.803464,bar,Yogen Fruz,{'name:en': 'Yogen Fruz'},Yogen Früz
5009,49.226578,-123.000636,bar,Yogen Fruz,"{'level': '0', 'name:en': 'Yogen Fruz'}",Yogen Früz
5010,49.286674,-123.128309,ice_cream,Yogen Früz,"{'brand:wikidata': 'Q8054358', 'addr:housenumb...",Yogen Früz
2463,49.275335,-123.123731,fast_food,Menchie's Frozen Yogourt,"{'addr:housenumber': '412', 'drive_through': '...",Menchie's Frozen Yogurt
2464,49.218635,-122.955424,bar,Menchies Frozen Yoghurt,{'name:en': 'Menchies Frozen Yoghurt'},Menchie's Frozen Yogurt
2319,49.276624,-122.794802,ice_cream,Marble Slab Creamery,"{'brand:wikidata': 'Q17020087', 'addr:housenum...",Marble Slab Creamery
2318,49.117708,-122.670502,ice_cream,Marble Slab Creamery,"{'brand:wikidata': 'Q17020087', 'addr:housenum...",Marble Slab Creamery
2314,49.042768,-122.779738,ice_cream,Marble Slab Creamery,"{'brand:wikidata': 'Q17020087', 'addr:housenum...",Marble Slab Creamery
2317,49.191614,-122.947590,fast_food,Marble Slab Creamery,"{'cuisine': 'ice_cream', 'takeaway': 'yes'}",Marble Slab Creamery
2321,49.132632,-123.093106,ice_cream,Marble Slab Creamery,"{'brand:wikidata': 'Q17020087', 'cuisine': 'ic...",Marble Slab Creamery
2315,49.312395,-123.082122,ice_cream,Marble Slab Creamery,"{'addr:housenumber': '180', 'addr:street': 'We...",Marble Slab Creamery
2320,49.198372,-122.978172,ice_cream,Marble Slab Creamery,"{'brand:wikidata': 'Q17020087', 'cuisine': 'ic...",Marble Slab Creamery
2316,49.263404,-123.116226,ice_cream,Marble Slab Creamery,"{'brand:wikidata': 'Q17020087', 'addr:housenum...",Marble Slab Creamery
1029,49.163156,-122.661886,fast_food,Dairy Queen,"{'brand:wikidata': 'Q1141226', 'addr:housenumb...",Dairy Queen
1015,49.256783,-123.184916,fast_food,Dairy Queen,"{'brand:wikidata': 'Q1141226', 'brand:wikipedi...",Dairy Queen
1018,49.281211,-123.011999,fast_food,Dairy Queen,"{'payment:credit_cards': 'yes', 'drive_through...",Dairy Queen
1021,49.225764,-122.997835,fast_food,Dairy Queen,"{'brand:wikidata': 'Q1141226', 'level': '1', '...",Dairy Queen
1031,49.089991,-123.080656,fast_food,Dairy Queen,"{'brand:wikidata': 'Q1141226', 'brand:wikipedi...",Dairy Queen
1016,49.230899,-123.090798,fast_food,Dairy Queen,{},Dairy Queen
1023,49.337224,-123.039389,fast_food,Dairy Queen,"{'brand:wikidata': 'Q1141226', 'cuisine': 'ice...",Dairy Queen
1030,49.039621,-122.801585,fast_food,Dairy Queen,"{'brand:wikidata': 'Q1141226', 'addr:housenumb...",Dairy Queen
1013,49.235928,-123.044715,fast_food,Dairy Queen,"{'brand:wikidata': 'Q1141226', 'brand:wikipedi...",Dairy Queen
1014,49.328507,-123.161746,fast_food,Dairy Queen,"{'brand:wikidata': 'Q1141226', 'addr:housenumb...",Dairy Queen
1034,49.239072,-123.065003,fast_food,Dairy Queen,{'url': 'http://www.dairyqueen.com/us-en/store...,Dairy Queen
1027,49.105009,-122.659889,fast_food,Dairy Queen,"{'brand:wikidata': 'Q1141226', 'addr:housenumb...",Dairy Queen
1019,49.030851,-123.069185,fast_food,Dairy Queen,"{'brand:wikidata': 'Q1141226', 'cuisine': 'ice...",Dairy Queen
1032,49.235694,-122.864871,fast_food,Dairy Queen,{'alt_name': 'Dairy Queen'},Dairy Queen
1025,49.259422,-123.100879,fast_food,Dairy Queen,"{'brand:wikidata': 'Q1141226', 'addr:housenumb...",Dairy Queen
1028,49.227279,-123.000150,fast_food,Dairy Queen,"{'brand:wikidata': 'Q1141226', 'level': '0', '...",Dairy Queen
1024,49.280169,-122.966569,fast_food,Dairy Queen,"{'brand:wikidata': 'Q1141226', 'cuisine': 'ice...",Dairy Queen
1026,49.168565,-122.800964,fast_food,Dairy Queen,"{'brand:wikidata': 'Q1141226', 'cuisine': 'ice...",Dairy Queen
1020,49.218384,-122.653467,fast_food,Dairy Queen,"{'addr:housenumber': '20492', 'addr:street': '...",Dairy Queen
1033,49.271335,-122.755624,fast_food,Dairy Queen,{},Dairy Queen
1017,49.113970,-122.669951,fast_food,Dairy Queen,"{'brand:wikidata': 'Q1141226', 'internet_acces...",Dairy Queen
1022,49.148739,-123.135898,fast_food,Dairy Queen,"{'cuisine': 'ice_cream', 'addr:housenumber': '...",Dairy Queen
280,49.114481,-122.680051,ice_cream,Baskin-Robbins,"{'brand:wikidata': 'Q584601', 'addr:housenumbe...",Baskin-Robbins
279,49.374243,-123.273188,ice_cream,Baskin-Robbins,"{'brand:wikidata': 'Q584601', 'addr:housenumbe...",Baskin-Robbins

In [20]:
hamburger = pd.read_csv("hamburger.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, hamburger['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
hamburger = amenities[amenities['closest_name'] != '']
hamburger.to_json('hamburger.json', orient='records', lines=True)
hamburger

,lat,lon,amenity,name,tags,closest_name
3252,49.252490,-122.898259,restaurant,Red Robin,{},Red Robin
3253,49.284623,-123.125267,restaurant,Red Robin,"{'brand:wikidata': 'Q7304886', 'official_name'...",Red Robin
3251,49.217228,-122.593651,restaurant,Red Robin,"{'brand:wikidata': 'Q7304886', 'official_name'...",Red Robin

In [21]:
hamburger_ff = pd.read_csv("hamburgers-fast-food.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, hamburger_ff['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
hamburger_ff = amenities[amenities['closest_name'] != '']
hamburger_ff.to_json('hamburger_fast_food.json', orient='records', lines=True)
hamburger_ff

,lat,lon,amenity,name,tags,closest_name
4879,49.169176,-122.958658,fast_food,Wendy's,{'opening_hours': 'Mo-Fr 10:00-20:00; Sa-Su 10...,Wendy's
4883,49.259894,-122.757027,fast_food,Wendy's,"{'opening_hours': 'Mo-Su 10:00-01:00', 'addr:h...",Wendy's
4876,49.246945,-122.749999,fast_food,Wendy's,"{'brand:wikidata': 'Q550258', 'addr:housenumbe...",Wendy's
4877,49.060451,-122.382810,fast_food,Wendy's,"{'opening_hours': '10:00-02:00', 'cuisine': 'b...",Wendy's
4886,49.196035,-123.177165,fast_food,Wendy's,"{'brand:wikidata': 'Q550258', 'addr:housenumbe...",Wendy's
...,...,...,...,...,...,...
582,49.190925,-122.890884,fast_food,Burger King,"{'cuisine': 'burger', 'drive_through': 'yes'}",Burger King
574,49.186768,-122.849939,fast_food,Burger King,"{'brand:wikidata': 'Q177054', 'brand:wikipedia...",Burger King
585,49.284139,-123.114291,fast_food,Burger King,"{'brand:wikidata': 'Q177054', 'addr:housenumbe...",Burger King
580,49.190425,-122.844893,fast_food,Burger King,"{'brand:wikidata': 'Q177054', 'wheelchair': 'y...",Burger King
91,49.225965,-123.002616,restaurant,A&W Restaurant,"{'level': '1', 'name:en': 'A&W Restaurant'}",A&W Restaurants

In [22]:
hotdog = pd.read_csv("hotdogs-fast-food.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, hotdog['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
hotdog = amenities[amenities['closest_name'] != '']
#hotdog.to_json('hotdog.json', orient='records', lines=True)
hotdog

Empty DataFrame
Columns: [lat, lon, amenity, name, tags, closest_name]
Index: []

In [23]:
italian = pd.read_csv("italian.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, italian['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
italian = amenities[amenities['closest_name'] != '']
italian.to_json('italian.json', orient='records', lines=True)
italian

,lat,lon,amenity,name,tags,closest_name
4419,49.283844,-123.105367,restaurant,The Old Spaghetti Factory,"{'diet:vegetarian': 'yes', 'addr:housenumber':...",The Old Spaghetti Factory
4416,49.134334,-123.065142,restaurant,The Old Spaghetti Factory,"{'cuisine': 'italian', 'addr:housenumber': '14...",The Old Spaghetti Factory
4418,49.169469,-122.665755,restaurant,The Old Spaghetti Factory,"{'addr:housenumber': '20077', 'addr:street': '...",The Old Spaghetti Factory
4417,49.201896,-122.912651,restaurant,The Old Spaghetti Factory,"{'wheelchair': 'limited', 'addr:housenumber': ...",The Old Spaghetti Factory
2731,49.112990,-122.666724,restaurant,Olive Garden,"{'brand:wikidata': 'Q3045312', 'website': 'htt...",Olive Garden

In [24]:
mexican = pd.read_csv("mexican.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, mexican['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
mexican = amenities[amenities['closest_name'] != '']
#mexican.to_json('mexican.json', orient='records', lines=True)
mexican

Empty DataFrame
Columns: [lat, lon, amenity, name, tags, closest_name]
Index: []

In [25]:
mexican_ff = pd.read_csv("mexican-fast-food.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, mexican_ff['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
mexican_ff = amenities[amenities['closest_name'] != '']
mexican_ff.to_json('mexican_fast_food.json', orient='records', lines=True)
mexican_ff

,lat,lon,amenity,name,tags,closest_name
4180,49.130952,-122.319302,fast_food,Taco Del Mar,"{'brand:wikidata': 'Q7673972', 'website': 'htt...",Taco del Mar
4185,49.163383,-122.659492,fast_food,Taco Del Mar,"{'brand:wikidata': 'Q7673972', 'brand:wikipedi...",Taco del Mar
4181,49.190837,-122.949679,fast_food,Taco Del Mar,"{'brand:wikidata': 'Q7673972', 'cuisine': 'mex...",Taco del Mar
4183,49.040692,-122.220178,fast_food,Taco Del Mar,"{'brand:wikidata': 'Q7673972', 'cuisine': 'mex...",Taco del Mar
4184,49.132300,-123.091493,fast_food,Taco Del Mar,"{'brand:wikidata': 'Q7673972', 'cuisine': 'mex...",Taco del Mar
4186,49.271732,-123.094881,fast_food,Taco Del Mar,"{'brand:wikidata': 'Q7673972', 'addr:housenumb...",Taco del Mar
4182,49.236639,-122.852996,fast_food,Taco Del Mar,"{'cuisine': 'mexican', 'source': 'survey'}",Taco del Mar
4188,49.279928,-123.106678,fast_food,Taco Time,"{'brand:wikidata': 'Q7673969', 'level': '1', '...",Taco Time
4189,49.114246,-122.675617,fast_food,Taco Time,"{'brand:wikidata': 'Q7673969', 'cuisine': 'mex...",Taco Time
4177,49.161479,-122.891070,fast_food,Taco Bell,"{'brand:wikidata': 'Q752941', 'cuisine': 'tex-...",Taco Bell
4179,49.277841,-122.795130,fast_food,Taco Bell,"{'brand:wikidata': 'Q752941', 'cuisine': 'tex-...",Taco Bell
4178,49.217136,-122.606489,fast_food,Taco Bell,"{'brand:wikidata': 'Q752941', 'addr:housenumbe...",Taco Bell
651,49.286819,-123.128521,cafe,Cafe Rico,"{'opening_hours': 'Mo-Th 07:00-01:00; Fr,Sa 07...",Cafe Rio

In [26]:
pizza = pd.read_csv("pizza.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, pizza['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
pizza = amenities[amenities['closest_name'] != '']
pizza.to_json('pizza.json', orient='records', lines=True)
pizza

,lat,lon,amenity,name,tags,closest_name
3337,49.119330,-122.823588,restaurant,Round Table Pizza,"{'cuisine': 'pizza', 'website': 'http://roundt...",Round Table Pizza
3339,49.154791,-123.125782,fast_food,Round Table Pizza,"{'cuisine': 'pizza', 'website': 'https://round...",Round Table Pizza
3338,49.165366,-122.661488,restaurant,Round Table Pizza,"{'brand:wikidata': 'Q7371139', 'cuisine': 'piz...",Round Table Pizza

In [27]:
pizza_italian = pd.read_csv("pizza-and-italian-fast-food.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, pizza_italian['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
pizza_italian = amenities[amenities['closest_name'] != '']
pizza_italian.to_json('pizza_italian_fast_food.json', orient='records', lines=True)
pizza_italian

,lat,lon,amenity,name,tags,closest_name
3058,49.231764,-123.009163,restaurant,Pizza Hut,"{'brand:wikidata': 'Q191615', 'addr:housenumbe...",Pizza Hut
3047,49.280843,-123.004131,fast_food,Pizza Hut,"{'addr:housenumber': '4448', 'addr:street': 'H...",Pizza Hut
3051,49.277858,-122.911985,restaurant,Pizza Hut,"{'brand:wikidata': 'Q191615', 'addr:housenumbe...",Pizza Hut
3056,49.217944,-122.648399,restaurant,Pizza Hut,"{'brand:wikidata': 'Q191615', 'cuisine': 'pizz...",Pizza Hut
3062,49.186938,-122.800062,restaurant,Pizza Hut,"{'brand:wikidata': 'Q191615', 'addr:housenumbe...",Pizza Hut
3052,49.268152,-123.146321,restaurant,Pizza Hut,"{'brand:wikidata': 'Q191615', 'addr:housenumbe...",Pizza Hut
3059,49.158393,-122.780223,restaurant,Pizza Hut,"{'addr:housenumber': '15951', 'cuisine': 'pizz...",Pizza Hut
3044,49.249256,-122.867065,restaurant,Pizza Hut,"{'cuisine': 'pizza', 'operator': 'Yum! Brands'}",Pizza Hut
3046,49.254491,-123.101278,restaurant,Pizza Hut,"{'brand:wikidata': 'Q191615', 'addr:housenumbe...",Pizza Hut
3061,49.031154,-123.069197,restaurant,Pizza Hut,"{'brand:wikidata': 'Q191615', 'cuisine': 'pizz...",Pizza Hut
3042,49.229388,-123.090498,restaurant,Pizza Hut,"{'brand:wikidata': 'Q191615', 'cuisine': 'pizz...",Pizza Hut
3049,49.263743,-123.210410,restaurant,Pizza Hut,"{'brand:wikidata': 'Q191615', 'addr:housenumbe...",Pizza Hut
3048,49.090879,-123.083367,restaurant,Pizza Hut,"{'brand:wikidata': 'Q191615', 'cuisine': 'pizz...",Pizza Hut
3045,49.051327,-122.692108,fast_food,Pizza Hut,{},Pizza Hut
3060,49.275881,-122.790978,restaurant,Pizza Hut,"{'brand:wikidata': 'Q191615', 'addr:province':...",Pizza Hut
3041,49.166016,-122.663550,restaurant,Pizza Hut,"{'brand:wikidata': 'Q191615', 'addr:housenumbe...",Pizza Hut
3057,49.170954,-123.182440,restaurant,Pizza Hut,"{'cuisine': 'pizza', 'name:en': 'Pizza Hut'}",Pizza Hut
3043,49.132705,-122.339004,restaurant,Pizza Hut,"{'brand:wikidata': 'Q191615', 'website': 'http...",Pizza Hut
3054,49.198024,-122.978534,restaurant,Pizza Hut,"{'brand:wikidata': 'Q191615', 'addr:housenumbe...",Pizza Hut
3050,49.058954,-122.492274,restaurant,Pizza Hut,"{'brand:wikidata': 'Q191615', 'cuisine': 'pizz...",Pizza Hut
3055,49.212149,-123.140902,restaurant,Pizza Hut,"{'brand:wikidata': 'Q191615', 'addr:housenumbe...",Pizza Hut
3053,49.133789,-122.840663,restaurant,Pizza Hut,"{'brand:wikidata': 'Q191615', 'addr:housenumbe...",Pizza Hut
3063,49.335906,-123.037610,restaurant,Pizza Hut,"{'brand:wikidata': 'Q191615', 'cuisine': 'pizz...",Pizza Hut
2867,49.124521,-122.702173,fast_food,Papa Murphy's,"{'brand:wikidata': 'Q7132349', 'addr:province'...",Papa Murphy's
2866,49.045959,-122.797372,fast_food,Papa Murphy's,"{'brand:wikidata': 'Q7132349', 'addr:province'...",Papa Murphy's
2200,49.230811,-123.090808,fast_food,Little Caesars,"{'brand:wikidata': 'Q1393809', 'addr:housenumb...",Little Caesars
2205,49.271809,-122.755646,fast_food,Little Caesars,{'cuisine': 'pizza'},Little Caesars
2192,49.316361,-122.970652,fast_food,Little Caesars,"{'brand:wikidata': 'Q1393809', 'brand:wikipedi...",Little Caesars
2203,49.155793,-122.912847,fast_food,Little Caesars,"{'brand:wikidata': 'Q1393809', 'addr:housenumb...",Little Caesars
2199,49.039974,-122.269016,fast_food,Little Caesars,"{'cuisine': 'pizza', 'website': 'https://littl...",Little Caesars
2201,49.248512,-122.865974,fast_food,Little Caesars,"{'brand:wikidata': 'Q1393809', 'brand:wikipedi...",Little Caesars
2197,49.116790,-122.679583,fast_food,Little Caesars,"{'brand:wikidata': 'Q1393809', 'addr:housenumb...",Little Caesars
2194,49.120634,-122.891779,fast_food,Little Caesars,"{'brand:wikidata': 'Q1393809', 'cuisine': 'piz...",Little Caesars
2204,49.132093,-122.322059,fast_food,Little Caesars,"{'brand:wikidata': 'Q1393809', 'cuisine': 'piz...",Little Caesars
2198,49.219808,-122.646793,fast_food,Little Caesars,"{'brand:wikidata': 'Q1393809', 'addr:province'...",Little Caesars
2193,49.050933,-122.338484,fast_food,Little Caesars,"{'brand:wikidata': 'Q1393809', 'website': 'htt...",Little Caesars
2196,49.337148,-123.039392,fast_food,Little Caesars,"{'brand:wikidata': 'Q1393809', 'cuisine': 'piz...",Little Caesars
2207,49.222813,-122.983593,fast_food,Little Caesars,"{'brand:wikidata': 'Q1393809', 'addr:housenumb...",Little Caesars
2195,49.219530,-123.040814,fast_food,Little Caesars,"{'brand:wikidata': 'Q1393809', 'cuisine': 'piz...",Little Caesars
2206,49.089411,-123.080201,fast_food,Little Caesars,"{'brand:wikidata': 'Q1393809', 'cuisine': 'piz...",Little Caesars
2202,49.282310,-122.800398,fast_food,Little Caesars,"{'brand:wikidata': 'Q1393809', 'addr:province'...",Little Caesars
2208,49.154460,-123.124750,fast_food,Little Caesars,"{'addr:housenumber': '195-9040', 'addr:street'...",Little Caesars
1829,49.047966,-122.339000,restaurant,J's Pizza,"{'website': 'http://www.jspizza.ca', 'phone': ...",Jet's Pizza
1830,49.055407,-122.271957,restaurant,J's Pizza,"{'alt_name': 'J's Pizza & Grill', 'website': '...",Jet's Pizza
1143,49.233649,-123.036118,fast_food,Domino's,"{'brand:wikidata': 'Q839466', 'addr:housenumbe...",Domino's
1140,49.278708,-122.806674,fast_food,Domino's,"{'brand:wikidata': 'Q839466', 'brand:wikipedia...",Domino's
1144,49.251066,-123.078682,fast_food,Domino's,"{'brand:wikidata': 'Q839466', 'addr:housenumbe...",Domino's
1136,49.262661,-123.091518,fast_food,Domino's,"{'brand:wikidata': 'Q839466', 'addr:province':...",Domino's
1138,49.277654,-123.125186,fast_food,Domino's,"{'brand:wikidata': 'Q839466', 'addr:province':...",Domino's
1137,49.075926,-122.670154,fast_food,Domino's,"{'brand:wikidata': 'Q839466', 'addr:province':...",Domino's
1142,49.183865,-123.092964,fast_food,Domino's,"{'brand:wikidata': 'Q839466', 'cuisine': 'pizz...",Domino's
1139,49.115663,-122.682302,fast_food,Domino's,"{'brand:wikidata': 'Q839466', 'brand:wikipedia...",Domino's
1141,49.221814,-122.996932,fast_food,Domino's,"{'brand:wikidata': 'Q839466', 'delivery': 'yes...",Domino's

In [28]:
pizza = pd.read_csv("pizza.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, pizza['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
pizza = amenities[amenities['closest_name'] != '']
pizza.to_json('pizza.json', orient='records', lines=True)
pizza

,lat,lon,amenity,name,tags,closest_name
3338,49.165366,-122.661488,restaurant,Round Table Pizza,"{'brand:wikidata': 'Q7371139', 'cuisine': 'piz...",Round Table Pizza
3337,49.119330,-122.823588,restaurant,Round Table Pizza,"{'cuisine': 'pizza', 'website': 'http://roundt...",Round Table Pizza
3339,49.154791,-123.125782,fast_food,Round Table Pizza,"{'cuisine': 'pizza', 'website': 'https://round...",Round Table Pizza

In [29]:
salad_vegan = pd.read_csv("salad-vegan.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, salad_vegan['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
salad_vegan = amenities[amenities['closest_name'] != '']
#salad_vegan.to_json('salad_vegan.json', orient='records', lines=True)
salad_vegan

Empty DataFrame
Columns: [lat, lon, amenity, name, tags, closest_name]
Index: []

In [30]:
sandwiches = pd.read_csv("sandwiches.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, sandwiches['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
sandwiches = amenities[amenities['closest_name'] != '']
#sandwiches.to_json('pizza.json', orient='records', lines=True)
sandwiches

Empty DataFrame
Columns: [lat, lon, amenity, name, tags, closest_name]
Index: []

In [31]:
sandwiches_ff = pd.read_csv("sandwiches-fast-food.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, sandwiches_ff['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
sandwiches_ff = amenities[amenities['closest_name'] != '']
sandwiches_ff.to_json('sandwiches_fast_food.json', orient='records', lines=True)
sandwiches_ff

,lat,lon,amenity,name,tags,closest_name
4017,49.154897,-123.157880,fast_food,Subway,"{'brand:wikidata': 'Q244457', 'cuisine': 'sand...",Subway
3996,49.263501,-122.887030,fast_food,Subway,"{'brand:wikidata': 'Q244457', 'cuisine': 'sand...",Subway
3929,49.191379,-122.844903,fast_food,Subway,"{'brand:wikidata': 'Q244457', 'addr:housenumbe...",Subway
3917,49.140146,-123.137885,fast_food,Subway,{'cuisine': 'sub'},Subway
3974,49.288731,-123.128133,fast_food,Subway,"{'brand:wikidata': 'Q244457', 'addr:province':...",Subway
...,...,...,...,...,...,...
3019,49.119491,-122.665255,fast_food,Pita Pit,"{'brand:wikidata': 'Q7757289', 'cuisine': 'pit...",Pita Pit
3020,49.054538,-122.370665,fast_food,Pita Pit,{'cuisine': 'sandwich'},Pita Pit
758,49.187115,-122.849458,fast_food,Charleys Philly Steaks,"{'brand:wikidata': 'Q1066777', 'cuisine': 'san...",Charleys Philly Steaks
178,49.039904,-123.088862,fast_food,Arby's,"{'brand:wikidata': 'Q630866', 'addr:housenumbe...",Arby's
177,49.060047,-122.493842,fast_food,Arby's,"{'brand:wikidata': 'Q630866', 'cuisine': 'sand...",Arby's

In [32]:
seafood = pd.read_csv("seafood.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, seafood['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
seafood = amenities[amenities['closest_name'] != '']
#seafood.to_json('seafood.json', orient='records', lines=True)
seafood

Empty DataFrame
Columns: [lat, lon, amenity, name, tags, closest_name]
Index: []

In [33]:
seafood_ff = pd.read_csv("seafood-fast-food.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, seafood_ff['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
seafood_ff = amenities[amenities['closest_name'] != '']
#seafood_ff.to_json('seafood_fast_food.json', orient='records', lines=True)
seafood_ff

Empty DataFrame
Columns: [lat, lon, amenity, name, tags, closest_name]
Index: []

In [34]:
southern_barbecue = pd.read_csv("southern-barbecue.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, southern_barbecue['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
southern_barbecue = amenities[amenities['closest_name'] != '']
#southern_barbecue.to_json('southern_barbecue.json', orient='records', lines=True)
southern_barbecue

Empty DataFrame
Columns: [lat, lon, amenity, name, tags, closest_name]
Index: []

In [35]:
steakhouse = pd.read_csv("steakhouse.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, steakhouse['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
steakhouse = amenities[amenities['closest_name'] != '']
#steakhouse.to_json('steakhouse.json', orient='records', lines=True)
steakhouse

Empty DataFrame
Columns: [lat, lon, amenity, name, tags, closest_name]
Index: []

In [36]:
vegetarian_vegan_ff = pd.read_csv("vegetarian-vegan-fast-food.csv")
amenities['closest_name'] = amenities['name'].apply(lambda title: difflib.get_close_matches(title, vegetarian_vegan_ff['Name'].values, 1, .85))
amenities = amenities.sort_values(by=['closest_name'], ascending=False)
amenities['closest_name'] = amenities['closest_name'].apply(lambda title: ''.join(title)) 
vegetarian_vegan_ff = amenities[amenities['closest_name'] != '']
#vegetarian_vegan_ff.to_json('vegetarian_vegan_fast_food.json', orient='records', lines=True)
vegetarian_vegan_ff

Empty DataFrame
Columns: [lat, lon, amenity, name, tags, closest_name]
Index: []